export const ORIGIN_ITEM = 'origin'
export const USER_ITEM = 'user'
export const EULA_VERSION_ITEM = 'eulaVersion'
export const BOX_ACCESS_TOKEN_ITEM = 'BoxAccessToken'
export const GDRIVE_ACCESS_TOKEN_ITEM = 'GDriveAccessToken'
export const DROPBOX_ACCESS_TOKEN_ITEM = 'DropboxAccessToken'
